### ISSUE TITLE
sm2签名验签有问题

### ISSUE THREAD

**Issue by qq1176914912** [yinggegit/DataConverter#3]
使用这个工具 自己签名 然后自己验签过不去
![image](https://user-images.githubusercontent.com/79817742/211970656-c07a381a-d474-45ba-91dd-1683722f90c5.png)

**Comment by yinggegame** [comment]
签名：

[image: image.png]

验证签名
[image: image.png]

签名，右边输入框内容保持不变，然后验证没问题，
版本如下：

[image: image.png]


无聊的测试玩家 ***@***.***> 于2023年1月12日周四 11:43写道：

**Comment by yinggegame** [comment]
还可以尝试点击 KeyGen，重新生成一组SM2的密钥

ge ying ***@***.***> 于2023年1月12日周四 22:35写道：
